---
transport:
  max_ssh_sessions: 6 # Workaround https://github.com/test-kitchen/test-kitchen/issues/1035

driver:
  name: docker
  use_sudo: false
  privileged: true
  provision_command: /usr/sbin/sshd -o UseDNS=no -o UsePAM=no -o PasswordAuthentication=yes -o UsePrivilegeSeparation=no -o PidFile=/tmp/sshd.pid

platforms:
  - name: centos-7
    driver:
      run_command: /usr/sbin/init
      provision_command:
        - yum install net-tools -y
        - yum install iproute -y
        - yum install nc -y
  - name: ubuntu-16.04
    driver:
      run_command: /sbin/init
      provision_command:
        - apt-get install netcat -y

provisioner:
  name: ansible_playbook
  hosts: localhost
  role_name: contentwise.kafka
  ansible_verbose: true
  idempotency_test: true
  require_chef_for_busser: true
  require_ruby_for_busser: false
  requirements_path: test/integration/requirements.yml

suites:
  - name: default